[settings.confirm]
delete_offset = [0, 0, 70, 20]
delete_origin = "center"
delete_title = "Permanently delete {n} selected file{s}?"
overwrite_content = "Will overwrite the following file:"
overwrite_offset = [0, 0, 50, 15]
overwrite_origin = "center"
overwrite_title = "Overwrite file?"
quit_content = "The following tasks are still running, are you sure you want to quit?"
quit_offset = [0, 0, 50, 15]
quit_origin = "center"
quit_title = "Quit?"
trash_offset = [0, 0, 70, 20]
trash_origin = "center"
trash_title = "Trash {n} selected file{s}?"

[settings.input]
cd_offset = [0, 2, 50, 3]
cd_origin = "top-center"
cd_title = "Change directory:"
create_offset = [0, 2, 50, 3]
create_origin = "top-center"
create_title = ["Create:", "Create (dir):"]
cursor_blink = false
filter_offset = [0, 2, 50, 3]
filter_origin = "top-center"
filter_title = "Filter:"
find_offset = [0, 2, 50, 3]
find_origin = "top-center"
find_title = ["Find next:", "Find previous:"]
rename_offset = [0, 1, 50, 3]
rename_origin = "hovered"
rename_title = "Rename:"
search_offset = [0, 2, 50, 3]
search_origin = "top-center"
search_title = "Search via {n}:"
shell_offset = [0, 2, 50, 3]
shell_origin = "top-center"
shell_title = ["Shell:", "Shell (block):"]

[settings.manager]
linemode = "none"
mouse_events = ["click", "scroll"]
ratio = [1, 4, 3]
scrolloff = 5
show_hidden = false
show_symlink = true
sort_by = "alphabetical"
sort_dir_first = true
sort_reverse = false
sort_sensitive = false
sort_translit = false
title_format = "Yazi: {cwd}"

[[settings.open.rules]]
name = "*/"
use = ["edit", "open", "reveal"]

[[settings.open.rules]]
mime = "text/*"
use = ["edit", "reveal"]

[[settings.open.rules]]
mime = "image/*"
use = ["open", "reveal"]

[[settings.open.rules]]
mime = "{audio,video}/*"
use = ["play", "reveal"]

[[settings.open.rules]]
mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}"
use = ["extract", "reveal"]

[[settings.open.rules]]
mime = "application/{json,ndjson}"
use = ["edit", "reveal"]

[[settings.open.rules]]
mime = "*/javascript"
use = ["edit", "reveal"]

[[settings.open.rules]]
mime = "inode/empty"
use = ["edit", "reveal"]

[[settings.open.rules]]
name = "*"
use = ["open", "reveal"]

[[settings.opener.edit]]
block = true
desc = "$EDITOR"
for = "unix"
run = "EDITOR:-vi \"$@\""

[[settings.opener.edit]]
desc = "code"
for = "windows"
orphan = true
run = "code %*"

[[settings.opener.edit]]
block = true
desc = "code (block)"
for = "windows"
run = "code -w %*"

[[settings.opener.extract]]
desc = "Extract here"
for = "unix"
run = "ya pub extract --list \"$@\""

[[settings.opener.extract]]
desc = "Extract here"
for = "windows"
run = "ya pub extract --list %*"

[[settings.opener.open]]
desc = "Open"
for = "linux"
run = "xdg-open \"$1\""

[[settings.opener.open]]
desc = "Open"
for = "macos"
run = "open \"$@\""

[[settings.opener.open]]
desc = "Open"
for = "windows"
orphan = true
run = "start \"\" \"%1\""

[[settings.opener.open]]
desc = "Open"
for = "android"
run = "termux-open \"$1\""

[[settings.opener.play]]
for = "unix"
orphan = true
run = "mpv --force-window \"$@\""

[[settings.opener.play]]
for = "windows"
orphan = true
run = "mpv --force-window %*"

[[settings.opener.play]]
block = true
desc = "Show media info"
for = "unix"
run = "mediainfo \"$1\"; echo \"Press enter to exit\"; read _"

[[settings.opener.reveal]]
desc = "Reveal"
for = "linux"
run = "xdg-open \"$(dirname \"$1\")\""

[[settings.opener.reveal]]
desc = "Reveal"
for = "macos"
run = "open -R \"$1\""

[[settings.opener.reveal]]
desc = "Reveal"
for = "windows"
orphan = true
run = "explorer /select,\"%1\""

[[settings.opener.reveal]]
desc = "Reveal"
for = "android"
run = "termux-open \"$(dirname \"$1\")\""

[[settings.opener.reveal]]
block = true
desc = "Show EXIF"
for = "unix"
run = "exiftool \"$1\"; echo \"Press enter to exit\"; read _"

[settings.pick]
open_offset = [0, 1, 50, 7]
open_origin = "hovered"
open_title = "Open with:"

[[settings.plugin.fetchers]]
id = "mime"
name = "*"
prio = "high"
run = "mime"

[[settings.plugin.preloaders]]
mime = "image/{avif,hei?,jxl,svg+xml}"
run = "magick"

[[settings.plugin.preloaders]]
mime = "image/*"
run = "image"

[[settings.plugin.preloaders]]
mime = "video/*"
run = "video"

[[settings.plugin.preloaders]]
mime = "application/pdf"
run = "pdf"

[[settings.plugin.preloaders]]
mime = "font/*"
run = "font"

[[settings.plugin.preloaders]]
mime = "application/ms-opentype"
run = "font"

[[settings.plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"

[[settings.plugin.prepend_fetchers]]
id = "git"
name = "*/"
run = "git"

[[settings.plugin.previewers]]
name = "*/"
run = "folder"
sync = true

[[settings.plugin.previewers]]
mime = "text/*"
run = "code"

[[settings.plugin.previewers]]
mime = "application/{mbox,javascript,wine-extension-ini}"
run = "code"

[[settings.plugin.previewers]]
mime = "application/{json,ndjson}"
run = "json"

[[settings.plugin.previewers]]
mime = "image/{avif,hei?,jxl,svg+xml}"
run = "magick"

[[settings.plugin.previewers]]
mime = "image/*"
run = "image"

[[settings.plugin.previewers]]
mime = "video/*"
run = "video"

[[settings.plugin.previewers]]
mime = "application/pdf"
run = "pdf"

[[settings.plugin.previewers]]
mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}"
run = "archive"

[[settings.plugin.previewers]]
mime = "application/{debian*-package,redhat-package-manager,rpm,android.package-archive}"
run = "archive"

[[settings.plugin.previewers]]
mime = "application/{iso9660-image,qemu-disk,ms-wim,apple-diskimage}"
run = "archive"

[[settings.plugin.previewers]]
mime = "application/virtualbox-{vhd,vhdx}"
run = "archive"

[[settings.plugin.previewers]]
name = "*.{img,fat,ext,ext2,ext3,ext4,squashfs,ntfs,hfs,hfsx}"
run = "archive"

[[settings.plugin.previewers]]
mime = "font/*"
run = "font"

[[settings.plugin.previewers]]
mime = "application/ms-opentype"
run = "font"

[[settings.plugin.previewers]]
mime = "inode/empty"
run = "empty"

[[settings.plugin.previewers]]
name = "*"
run = "file"

[[settings.plugin.spotters]]
name = "*/"
run = "folder"

[[settings.plugin.spotters]]
mime = "text/*"
run = "code"

[[settings.plugin.spotters]]
mime = "application/{mbox,javascript,wine-extension-ini}"
run = "code"

[[settings.plugin.spotters]]
mime = "image/{avif,hei?,jxl,svg+xml}"
run = "magick"

[[settings.plugin.spotters]]
mime = "image/*"
run = "image"

[[settings.plugin.spotters]]
mime = "video/*"
run = "video"

[[settings.plugin.spotters]]
name = "*"
run = "file"

[settings.preview]
cache_dir = ""
image_delay = 30
image_filter = "triangle"
image_quality = 75
max_height = 900
max_width = 600
sixel_fraction = 15
tab_size = 2
ueberzug_offset = [0, 0, 0, 0]
ueberzug_scale = 1
wrap = "no"

[settings.tasks]
bizarre_retry = 3
image_alloc = 536870912
image_bound = [0, 0]
macro_workers = 10
micro_workers = 10
suppress_preload = false

[settings.which]
sort_by = "none"
sort_reverse = false
sort_sensitive = false
sort_translit = false
