add_newline = true
format = "$character"
palette = "base16"
right_format = "$nix_shell$hostname$directory$git_branch$git_state$git_status"

[character]
error_symbol = "[❯](red)"
success_symbol = "[❯](#b4befe)"
vimcmd_symbol = "[❮](#b4befe)"

[directory]
style = "#585b70"
truncate_to_repo = true
truncation_length = 4

[git_branch]
format = "[$symbol$branch]($style) "
style = "#585b70"
symbol = " "

[git_state]
format = "([$state( $progress_current/$progress_total)]($style)) "
style = "#585b70"

[git_status]
ahead = "⇡"
behind = "⇣"
conflicted = "~"
deleted = "✘"
diverged = "⇕"
format = "[($all_status$ahead_behind)]($style)"
modified = "!"
renamed = "»"
staged = "+"
stashed = "≡"
style = "#585b70"
untracked = "?"

[nix_shell]
format = "[$symbol]($style) "
style = "#585b70"
symbol = "󱄅"

[palettes.base16]
base00 = "#000000"
base01 = "#0f0f0f"
base02 = "#313244"
base03 = "#45475a"
base04 = "#585b70"
base05 = "#cdd6f4"
base06 = "#f5e0dc"
base07 = "#b4befe"
base08 = "#f38ba8"
base09 = "#fab387"
base0A = "#f9e2af"
base0B = "#a6e3a1"
base0C = "#94e2d5"
base0D = "#89b4fa"
base0E = "#cba6f7"
base0F = "#f2cdcd"
base10 = "#000000"
base11 = "#000000"
base12 = "#f38ba8"
base13 = "#f9e2af"
base14 = "#a6e3a1"
base15 = "#94e2d5"
base16 = "#89b4fa"
base17 = "#cba6f7"
black = "#000000"
blue = "#89b4fa"
bright-black = "#45475a"
bright-blue = "#89b4fa"
bright-cyan = "#94e2d5"
bright-green = "#a6e3a1"
bright-magenta = "#cba6f7"
bright-purple = "#cba6f7"
bright-red = "#f38ba8"
bright-white = "#b4befe"
bright-yellow = "#f9e2af"
brown = "#f2cdcd"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#cba6f7"
orange = "#fab387"
purple = "#cba6f7"
red = "#f38ba8"
white = "#cdd6f4"
yellow = "#f9e2af"
